### ISSUE TITLE
能渲染pos格式的流程图，思维导图吗？？

### ISSUE THREAD

**Issue by buzhangsan** [maqi1520/clone-processon#2]

**Comment by maqi1520** [comment]
> _No description provided._

官方 pos格式， 是可以下载的下载下来后就是一个 json，
![image](https://user-images.githubusercontent.com/9312044/147430674-10fc5564-139e-4215-9b73-9230840b3a87.png)
但我还不清楚这个 pos 如何使用
js 方式可以支持

**Comment by cdh1991** [comment]
是的，官方的系统还可以但是容量有限，如果你这个可以解析渲染这个pos，可能应用场景会很广泛

**Comment by maqi1520** [comment]
> 是的，官方的系统还可以但是容量有限，如果你这个可以解析渲染这个pos，可能应用场景会很广泛

可以的，感谢您提的建议，您那边需要的话我找个时间加加这个功能？

**Comment by cdh1991** [comment]
> > 是的，官方的系统还可以但是容量有限，如果你这个可以解析渲染这个pos，可能应用场景会很广泛
> 
> 可以的，感谢您提的建议，您那边需要的话我找个时间加加这个功能？

十分感谢，如果能实现的话

**Comment by maqi1520** [comment]
![image](https://user-images.githubusercontent.com/9312044/149762804-01ec4a72-db9d-4ae4-99b9-981205f5e1e6.png)
已支持

**Comment by maqi1520** [comment]
> 
如果你对我的服务满意，请点个star，未来会支持更多功能
